server:
    port: 8040
spring:
  profiles:
    active: dev
    include: secret
  web:
    resources:
      static-locations: classpath:/static/
  logging:
    level:
      com.ll.OpenAI: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE
      org.hibernate.orm.jdbc.extract: TRACE
      org.springframework.transaction.interceptor: TRACE